
POST {{HostAddress}}/api/v{{Version}}/message HTTP/1.1
Content-Type: application/json
X-API-KEY: {{ApiKey}}

{
  "type": "push",
  "externalClientID": "12345",
  "content": "Ahoj $@Jmeno@$ MessageHub",
  "subject": "Pozdrav z MessageHub ",
  "category": "WELCOME",
  "templateCode" : "Template3",
  "contentAttributes": [
    {
      "name": "Jmeno",
      "value": "John"
    }
  ]

}

